name: challenge
description: Dev challenge
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  # Tools
  easy_localization: ^3.0.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.0.2
  hexcolor: ^3.0.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3

  # GraphQL
  graphql_flutter: ^5.1.2
  graphql_flutter_bloc: ^1.0.0
  graph_repository:
    path: packages/graph_repository

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/