name: graph_repository
description: GraphQL Repository.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.3
  equatable: ^2.0.5
  graphql_flutter_bloc: ^1.0.0
  artemis: ^7.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.7.1